Repository SWENT-TEAM17/OratorAI, pull requests merged in 2024-11, with the labels that each got.

#78 fix : simplified CI Environment Variables and Decoding Process
  .github/workflows/build.yaml
Labels: bug

#136 Fix crashes in Offline Mode
  app/src/androidTest/java/com/github/se/orator/MainActivityTest.kt
  app/src/main/java/com/github/se/orator/MainActivity.kt
Labels: bug

#148 fix: use Type.kt constants for UI layout
  app/src/main/java/com/github/se/orator/MainActivity.kt
  app/src/main/java/com/github/se/orator/ui/offline/OfflinePracticeQuestionsScreen.kt
  app/src/main/java/com/github/se/orator/ui/offline/OfflineRecordingScreen.kt
  app/src/main/java/com/github/se/orator/ui/offline/OfflineScreen.kt
  app/src/main/java/com/github/se/orator/ui/offline/RecordingReviewScreen.kt
  app/src/main/java/com/github/se/orator/ui/theme/Theme.kt
Labels: documentation, enhancement

#151 feature: implement log out functionality on the profile screen
  app/src/androidTest/java/com/github/se/orator/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/github/se/orator/ui/profile/ProfileScreen.kt
Labels: enhancement

#159 Enhance Friends Screen: Profile Picture Functionality, Search Fixes, and Filtering Improvements
  app/src/androidTest/java/com/github/se/orator/ui/friends/FriendsUITests.kt
  app/src/main/java/com/github/se/orator/ui/friends/AddFriends.kt
  app/src/main/java/com/github/se/orator/ui/friends/FriendsScreen.kt
Labels: enhancement

#162 Outcome Feedback Feature and Test Fixes
  app/src/androidTest/java/com/github/se/orator/ui/overview/FeedbackScreenTest.kt
  app/src/androidTest/java/com/github/se/orator/ui/overview/SpeakingJobInterViewModuleTest.kt
  app/src/androidTest/java/com/github/se/orator/ui/overview/SpeakingPublicSpeakingTest.kt
  app/src/androidTest/java/com/github/se/orator/ui/overview/SpeakingSalesPitchModuletest.kt
  app/src/main/java/com/github/se/orator/MainActivity.kt
  app/src/main/java/com/github/se/orator/model/chatGPT/ChatViewModel.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfile.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfileRepositoryFirestore.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfileViewModel.kt
  app/src/main/java/com/github/se/orator/ui/authentification/SignIn.kt
  app/src/main/java/com/github/se/orator/ui/friends/FriendsScreen.kt
  app/src/main/java/com/github/se/orator/ui/offline/OfflinePracticeQuestionsScreen.kt
  app/src/main/java/com/github/se/orator/ui/offline/OfflineRecordingScreen.kt
  app/src/main/java/com/github/se/orator/ui/overview/ChatScreen.kt
  app/src/main/java/com/github/se/orator/ui/overview/FeedbackScreen.kt
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingJobInterviewModule.kt
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingPracticeModule.kt
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingPublicSpeakingModule.kt
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingSalesPitchModule.kt
  app/src/main/java/com/github/se/orator/ui/profile/ProfileScreen.kt
  app/src/test/java/com/github/se/orator/model/chatGPT/ChatViewModelTest.kt
  app/src/test/java/com/github/se/orator/model/profile/UserProfileRepositoryFirestoreTest.kt
Labels: enhancement
