Repository SWENT-TEAM17/OratorAI, pull requests merged in 2024-12, with the labels that each got.

#186 Feature/friendship management
  app/src/androidTest/java/com/github/se/orator/ui/friends/FriendsUITests.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfile.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfileRepository.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfileRepositoryFirestore.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfileViewModel.kt
  app/src/main/java/com/github/se/orator/ui/friends/AddFriends.kt
  app/src/main/java/com/github/se/orator/ui/friends/FriendsScreen.kt
  app/src/test/java/com/github/se/orator/model/profile/UserProfileRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/orator/model/profile/UserProfileViewModelTest.kt
Labels: enhancement

#187 Enhance Speaking Modules with Improved UI, Prompts, and Test Stability
  app/src/androidTest/java/com/github/se/orator/ui/overview/FeedbackScreenTest.kt
  app/src/androidTest/java/com/github/se/orator/ui/overview/SpeakingJobInterViewModuleTest.kt
  app/src/androidTest/java/com/github/se/orator/ui/overview/SpeakingPublicSpeakingTest.kt
  app/src/androidTest/java/com/github/se/orator/ui/overview/SpeakingSalesPitchModuletest.kt
  app/src/androidTest/java/com/github/se/orator/ui/speaking/SpeakingScreenTest.kt
  app/src/main/java/com/github/se/orator/MainActivity.kt
  app/src/main/java/com/github/se/orator/model/chatGPT/ChatViewModel.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfile.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfileRepository.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfileRepositoryFirestore.kt
  app/src/main/java/com/github/se/orator/model/profile/UserProfileViewModel.kt
  app/src/main/java/com/github/se/orator/model/speaking/AnalysisData.kt
  app/src/main/java/com/github/se/orator/model/symblAi/SpeakingViewModel.kt
  app/src/main/java/com/github/se/orator/ui/overview/ChatScreen.kt
  app/src/main/java/com/github/se/orator/ui/overview/InputFieldData.kt
  app/src/main/java/com/github/se/orator/ui/overview/PracticeContext.kt
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingJobInterviewModule.kt
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingPracticeModule.kt
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingPublicSpeakingModule.kt
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingSalesPitchModule.kt
  app/src/main/java/com/github/se/orator/ui/theme/Color.kt
  app/src/main/java/com/github/se/orator/ui/theme/Theme.kt
  app/src/test/java/com/github/se/orator/model/apiLink/ApiLinkViewModelTest.kt
  app/src/test/java/com/github/se/orator/model/chatGPT/ChatViewModelTest.kt
  app/src/test/java/com/github/se/orator/model/symblAi/SpeakingViewModelTest.kt
Labels: enhancement

#216 Feature/UI consistency improvements
  app/src/main/java/com/github/se/orator/ui/authentification/SignIn.kt
  app/src/main/java/com/github/se/orator/ui/friends/AddFriends.kt
  app/src/main/java/com/github/se/orator/ui/friends/FriendsScreen.kt
  app/src/main/java/com/github/se/orator/ui/friends/Leaderboard.kt
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingPracticeModule.kt
  app/src/main/java/com/github/se/orator/ui/profile/CreateProfile.kt
  app/src/main/java/com/github/se/orator/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/orator/ui/settings/SettingsScreen.kt
  app/src/main/java/com/github/se/orator/ui/theme/DimensionsFactory.kt
  app/src/main/java/com/github/se/orator/ui/theme/Theme.kt
  app/src/main/java/com/github/se/orator/ui/theme/ThemeExtensions.kt
  app/src/main/java/com/github/se/orator/ui/theme/Type.kt
Labels: bug

#230 Enhance feedback generation based on number of responses
  app/src/androidTest/java/com/github/se/orator/ui/overview/FeedbackScreenTest.kt
  app/src/main/java/com/github/se/orator/model/chatGPT/ChatViewModel.kt
  app/src/main/java/com/github/se/orator/ui/overview/FeedbackScreen.kt
  app/src/test/java/com/github/se/orator/model/chatGPT/ChatViewModelTest.kt
Labels: enhancement

#229 228 implement take photo in profile screens
  app/src/androidTest/java/com/github/se/orator/ui/profile/CreateProfileTest.kt
  app/src/androidTest/java/com/github/se/orator/ui/profile/EditProfileTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/orator/ui/profile/CreateProfile.kt
  app/src/main/java/com/github/se/orator/ui/profile/EditProfile.kt
  app/src/main/res/xml/file_paths.xml
Labels: enhancement

#272 Feature : display friend name instead of other user in waiting for completion
  app/src/androidTest/java/com/github/se/orator/ui/battle/WaitingForCompletionScreenTest.kt
  app/src/main/java/com/github/se/orator/MainActivity.kt
  app/src/main/java/com/github/se/orator/ui/battle/WaitingForCompletionScreen.kt
Labels: enhancement

#277 fix : inconsistencies in speaking practice module dark mode
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingPracticeModule.kt
Labels: bug

#275 Fix : BOTI dark mode integration
  app/src/main/java/com/github/se/orator/ui/battle/BattleRequestSentScreen.kt
  app/src/main/java/com/github/se/orator/ui/battle/EvaluationScreen.kt
  app/src/main/java/com/github/se/orator/ui/battle/WaitingForCompletionScreen.kt
Labels: bug

#295 Fix : speaking practice module UI
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingPracticeModule.kt
Labels: bug

#280 feature: BOTI evaluation implementation
  app/src/androidTest/java/com/github/se/orator/ui/battle/EvaluationScreenTest.kt
  app/src/main/java/com/github/se/orator/MainActivity.kt
  app/src/main/java/com/github/se/orator/model/chatGPT/ChatViewModel.kt
  app/src/main/java/com/github/se/orator/model/speechBattle/BattleRepository.kt
  app/src/main/java/com/github/se/orator/model/speechBattle/BattleRepositoryFirestore.kt
  app/src/main/java/com/github/se/orator/model/speechBattle/BattleViewModel.kt
  app/src/main/java/com/github/se/orator/ui/battle/EvaluationScreen.kt
  app/src/main/java/com/github/se/orator/ui/battle/WaitingForCompletionScreen.kt
  app/src/test/java/com/github/se/orator/model/battle/BattleRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/orator/model/battle/BattleViewModelTest.kt
  app/src/test/java/com/github/se/orator/model/chatGPT/ChatViewModelTest.kt
Labels: enhancement

#296 fix: bottom navigation menu padding
  app/src/main/java/com/github/se/orator/ui/navigation/BottomNavigationMenu.kt
Labels: bug

#269 Save offline mode feedback + parallelize it
  app/src/androidTest/java/com/github/se/orator/ui/offline/OfflineInterviewModuleTest.kt
  app/src/androidTest/java/com/github/se/orator/ui/offline/OfflineRecordingScreenTest.kt
  app/src/androidTest/java/com/github/se/orator/ui/profile/OfflineRecordingsProfileTest.kt
  app/src/androidTest/java/com/github/se/orator/ui/profile/PreviousRecordingsFeedbackTest.kt
  app/src/main/java/com/github/se/orator/MainActivity.kt
  app/src/main/java/com/github/se/orator/model/chatGPT/ChatViewModel.kt
  app/src/main/java/com/github/se/orator/model/offlinePrompts/OfflinePromptsFunctions.kt
  app/src/main/java/com/github/se/orator/model/offlinePrompts/OfflinePromptsFunctionsInterface.kt
  app/src/main/java/com/github/se/orator/model/symblAi/SpeakingViewModel.kt
  app/src/main/java/com/github/se/orator/ui/offline/OfflineInterviewModule.kt
  app/src/main/java/com/github/se/orator/ui/offline/OfflinePromptsFunctionsImplementation.kt
  app/src/main/java/com/github/se/orator/ui/profile/OfflineRecordingsProfile.kt
  app/src/main/java/com/github/se/orator/ui/profile/PreviousRecordingsFeedback.kt
  app/src/test/java/com/github/se/orator/model/chatGPT/ChatViewModelTest.kt
  app/src/test/java/com/github/se/orator/model/symblAi/SpeakingViewModelTest.kt
  app/src/test/java/com/github/se/orator/offlinePrompts/OfflinePromptsTest.kt
Labels: enhancement

#299 feature: BOTI cancelling
  app/src/androidTest/java/com/github/se/orator/ui/battle/BattleChatScreenTest.kt
  app/src/main/java/com/github/se/orator/model/speechBattle/BattleViewModel.kt
  app/src/main/java/com/github/se/orator/ui/battle/BattleChatScreen.kt
  app/src/main/java/com/github/se/orator/ui/battle/BattleRequestSentScreen.kt
  app/src/main/java/com/github/se/orator/ui/battle/EvaluationScreen.kt
  app/src/main/java/com/github/se/orator/ui/overview/ChatScreen.kt
  app/src/main/java/com/github/se/orator/ui/theme/Color.kt
Labels: enhancement

#302 feature: BOTI popup screen
  app/src/androidTest/java/com/github/se/orator/ui/friends/FriendsUITests.kt
  app/src/main/java/com/github/se/orator/model/speechBattle/BattleViewModel.kt
  app/src/main/java/com/github/se/orator/ui/friends/FriendsScreen.kt
Labels: enhancement

#287 fix: top navigation bar UI
  app/src/androidTest/java/com/github/se/orator/ui/navigation/TopNavBarTest.kt
  app/src/main/java/com/github/se/orator/ui/battle/BattleRequestSentScreen.kt
  app/src/main/java/com/github/se/orator/ui/battle/EvaluationScreen.kt
  app/src/main/java/com/github/se/orator/ui/battle/WaitingForCompletionScreen.kt
  app/src/main/java/com/github/se/orator/ui/friends/AddFriends.kt
  app/src/main/java/com/github/se/orator/ui/friends/FriendsScreen.kt
  app/src/main/java/com/github/se/orator/ui/friends/Leaderboard.kt
  app/src/main/java/com/github/se/orator/ui/navigation/TopNavigationMenu.kt
  app/src/main/java/com/github/se/orator/ui/overview/ChatScreen.kt
  app/src/main/java/com/github/se/orator/ui/overview/FeedbackScreen.kt
  app/src/main/java/com/github/se/orator/ui/overview/SpeakingPracticeModule.kt
  app/src/main/java/com/github/se/orator/ui/profile/CreateProfile.kt
  app/src/main/java/com/github/se/orator/ui/profile/EditProfile.kt
  app/src/main/java/com/github/se/orator/ui/profile/OfflineRecordingsProfile.kt
  app/src/main/java/com/github/se/orator/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/orator/ui/settings/SettingsScreen.kt
  app/src/main/java/com/github/se/orator/ui/theme/Type.kt
Labels: enhancement

#315 fix: remove title battle screen
  app/src/main/java/com/github/se/orator/ui/battle/BattleScreen.kt
Labels: enhancement

#321 fix: ensure one eval boti
  app/src/main/java/com/github/se/orator/ui/battle/EvaluationScreen.kt
Labels: bug

#331 fix: dark mode for metrics display in feedback screen
  app/src/main/java/com/github/se/orator/ui/overview/FeedbackScreen.kt
Labels: bug

#324 fix: other user declines battle redirects to home screen
  app/src/androidTest/java/com/github/se/orator/ui/battle/BattleRequestSentScreen.kt
  app/src/main/java/com/github/se/orator/ui/battle/BattleRequestSentScreen.kt
Labels: bug, enhancement

#343 BOTI minor tweaks and adjustments
  app/src/androidTest/java/com/github/se/orator/ui/battle/EvaluationScreenTest.kt
  app/src/main/java/com/github/se/orator/model/chatGPT/ChatViewModel.kt
  app/src/main/java/com/github/se/orator/ui/battle/EvaluationScreen.kt
Labels: bug, enhancement

#290 enhancement: Include offline screens and speaking screens in the end to end tests
  app/src/androidTest/java/com/github/se/orator/endtoend/EndToEndTest.kt
  app/src/main/java/com/github/se/orator/model/symblAi/SpeakingRepository.kt
  app/src/main/java/com/github/se/orator/model/symblAi/SpeakingRepositoryRecord.kt
  app/src/main/java/com/github/se/orator/model/symblAi/SpeakingViewModel.kt
  app/src/main/java/com/github/se/orator/ui/offline/OfflineRecordingScreen.kt
Labels: enhancement
